# Generated by Django 6.0.3 on 2026-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
