# Generated by Django 6.0.3 on 2026-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Client', 'Client')], max_length=100),
        ),
    ]
