# Generated by Django 6.0.3 on 2026-03-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_budget_range_profile_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_freelancers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
