# Generated by Django 6.0.3 on 2026-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_saved_freelancers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Confirmation Pending', 'Confirmation Pending'), ('Active', 'Active'), ('Payment Rejected', 'Payment Rejected'), ('Completed', 'Completed')], default='Pending Payment', max_length=30),
        ),
    ]
