# Generated by Django 6.0.3 on 2026-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_otp_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='work_submission_file',
            field=models.FileField(blank=True, null=True, upload_to='work_submissions/'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Confirmation Pending', 'Confirmation Pending'), ('Funds Escrowed', 'Funds Escrowed'), ('Active', 'Active'), ('Work Submitted', 'Work Submitted'), ('Payment Rejected', 'Payment Rejected'), ('Completed', 'Completed'), ('Disputed', 'Disputed')], default='Pending Payment', max_length=30),
        ),
    ]
