# Generated by Django 6.0.3 on 2026-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_submitted_at_order_work_submission_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work_submission_file',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_submission_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Confirmation Pending', 'Confirmation Pending'), ('Active', 'Active'), ('Work Submitted', 'Work Submitted'), ('Payment Rejected', 'Payment Rejected'), ('Completed', 'Completed'), ('Disputed', 'Disputed')], default='Pending Payment', max_length=30),
        ),
    ]
