# Generated by Django 6.0.3 on 2026-03-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_work_submission_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
