# Generated by Django 6.0.3 on 2026-03-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Confirmation Pending', 'Confirmation Pending'), ('Active', 'Active'), ('Work Submitted', 'Work Submitted'), ('Revision Requested', 'Revision Requested'), ('Payment Rejected', 'Payment Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Disputed', 'Disputed')], default='Pending Payment', max_length=30),
        ),
    ]
