# Generated by Django 6.0.3 on 2026-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_is_banned_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
