# Generated by Django 6.0.3 on 2026-03-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_job_client'),
        ('api', '0015_profile_account_name'),
    ]

    operations = [
    ]
