# Generated by Django 6.0.3 on 2026-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_bio_profile_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shoot_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
