# Generated by Django 6.0.3 on 2026-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_location_order_shoot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
